export const masterdata = {
	"dwg_table": [
			
			{
			"id": 1,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "SP-P71P070",
			"DWGshtno": "1",
			"DWGrev": "0",
			"LNEidno": "Line-070-SP-P71",
			"DWGname": "Drawing-1E543",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 2,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "SP-P71P070",
			"DWGshtno": "2",
			"DWGrev": "0",
			"LNEidno": "Line-070-SP-P71",
			"DWGname": "Drawing-AC456",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 3,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "SP-P71P070",
			"DWGshtno": "3",
			"DWGrev": "0",
			"LNEidno": "Line-070-SP-P71",
			"DWGname": "Drawing-A25932",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 4,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "SP-P71P070",
			"DWGshtno": "4",
			"DWGrev": "1",
			"LNEidno": "Line-070-SP-P71",
			"DWGname": "Drawing-BB8",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 5,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "SP-P71P070",
			"DWGshtno": "5",
			"DWGrev": "0",
			"LNEidno": "Line-010-EK-P72",
			"DWGname": "Drawing-R2D2",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 6,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "HS-P10-210",
			"DWGshtno": "1",
			"DWGrev": "1",
			"LNEidno": "Line-210-HS-P10",
			"DWGname": "Drawing-789",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 7,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "HS-P10-210",
			"DWGshtno": "2",
			"DWGrev": "1",
			"LNEidno": "Line-210-HS-P10",
			"DWGname": "Drawing-ECS234",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 8,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "HS-P10-210",
			"DWGshtno": "3",
			"DWGrev": "0",
			"LNEidno": "Line-210-HS-P10",
			"DWGname": "Drawing-SNP500",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 9,
			"DWGiddate": "01/15/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "HS-P10-210",
			"DWGshtno": "4",
			"DWGrev": "0",
			"LNEidno": "Line-210-HS-P10",
			"DWGname": "Drawing-IPC3",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 11,
			"DWGiddate": "05/22/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "ML510-B-023_B",
			"DWGshtno": "1",
			"DWGrev": "0",
			"LNEidno": "Line-063-PP-P20",
			"DWGname": "Drawing-M2",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 12,
			"DWGiddate": "05/22/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "ML510-B-023_B",
			"DWGshtno": "1",
			"DWGrev": "0",
			"LNEidno": "Line-067-PP-P20",
			"DWGname": "Drawing-TI86",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 13,
			"DWGiddate": "05/24/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "ML376-J-057_B",
			"DWGshtno": "1",
			"DWGrev": "1",
			"LNEidno": "Line-057-J-P376",
			"DWGname": "Drawing-B737",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 14,
			"DWGiddate": "05/24/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "395-B-050_B",
			"DWGshtno": "1",
			"DWGrev": "0",
			"LNEidno": "Line-063-PP-P20",
			"DWGname": "Drawing-AT2650",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 15,
			"DWGiddate": "05/24/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "395-B-050_B",
			"DWGshtno": "1",
			"DWGrev": "0",
			"LNEidno": "Line-067-PP-P20",
			"DWGname": "Drawing-C5ER",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 18,
			"DWGiddate": "05/25/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "ISO",
			"DWGno": "ML510-K-064_B",
			"DWGshtno": "1",
			"DWGrev": "0",
			"LNEidno": "Line-050-LS-P519",
			"DWGname": "Drawing-M83",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},
			{
			"id": 20,
			"DWGiddate": "05/25/2022",
			"DWGdisc": "MECH. (PIPE)",
			"DWGtype": "PID",
			"DWGno": "ML510-C-208_B",
			"DWGshtno": "1",
			"DWGrev": "0",
			"LNEidno": "Line-545-FH-P10",
			"DWGname": "Drawing-L23",
			"DWGselect_add": false,
			"DWG_AB": false,
			"DWG_RL": false,
			"DWG_FLTR": false
			},

	],

	"line_list_table": [
			 {
			  "id": 1,
			  "LNEidedate": "01/17/2022",
			  "LNEno": "Line-210-HS-P10",
			  "LNEFrom": "Line-210-HS-P10",
			  "LNETo": "SLUDGE TANK 72085",
			  "LNEsystem": "MECHANICAL",
			  "LNEsysdes": "HS",
			  "LNEsysarea": "376",
			  "LNErefpid": "ML376-B-010",
			  "LNEsyscode": "B31.3N",
			  "LNEspec": "P10",
			  "LNEoptemp": 0,
			  "LNEdesignpress": "1102",
			  "LNEdesigntemp": "50",
			  "LNEdesigndens": 0,
			  "LNEpwht": false,
			  "LNE_VT": 100,
			  "LNE_RT": 0,
			  "LNE_MT": 0,
			  "LNE_PT": 0,
			  "LNE_UT": 0,
			  "LNE_HT": 0,
			  "LNE_MI": 0,
			  "LNEtesttype": "HYDRO",
			  "LNEtestmed": "N/A",
			  "LNEtestpress": 0,
			  "LNEinsulation": false,
			  "LNE_CA": 0,
			  "INRidno": 1,
			  "LNE_pickme": false
			 },
			 {
			  "id": 2,
			  "LNEidedate": "01/17/2022",
			  "LNEno": "Line-010-EK-P72",
			  "LNEFrom": "2\"-SP-P71",
			  "LNETo": "2\"-SP-32-070",
			  "LNEsystem": "MECHANICAL",
			  "LNEsysdes": "SP",
			  "LNEsysarea": "345",
			  "LNErefpid": "510-B-004_B",
			  "LNErefpidrev": "1",
			  "LNEsyscode": "B31.3N",
			  "LNEspec": "P71",
			  "LNEoptemp": 0,
			  "LNEdesignpress": "860",
			  "LNEdesigndens": 0,
			  "LNEpwht": false,
			  "LNE_VT": 100,
			  "LNE_RT": 0,
			  "LNE_MT": 0,
			  "LNE_PT": 0,
			  "LNE_UT": 0,
			  "LNE_HT": 0,
			  "LNE_MI": 0,
			  "LNEtestpack": "SP Service Test TP #5",
			  "LNEtesttype": "Hydro",
			  "LNEtestmed": "N/A",
			  "LNEtestpress": 1290,
			  "LNEcolor": "N/A",
			  "LNEtracing": "N/A",
			  "LNEinsulation": false,
			  "LNEInstype": "N/A",
			  "LNEinsTm": "N/A",
			  "LNE_CA": 0.0625,
			  "LNEflgrating": "150 lb",
			  "INRidno": 1,
			  "LNE_pickme": false
			 },
			 {
			  "id": 3,
			  "LNEidedate": "01/17/2022",
			  "LNEno": "Line-070-SP-P71",
			  "LNEFrom": "75-WP-09-563",
			  "LNETo": "3\"-SP-P20-070",
			  "LNEsystem": "MECHANICAL",
			  "LNEsysdes": "SP",
			  "LNEsysarea": "345",
			  "LNErefpid": "510-B-004_B",
			  "LNErefpidrev": "1",
			  "LNEsyscode": "B31.3N",
			  "LNEspec": "P71",
			  "LNEoptemp": 0,
			  "LNEdesignpress": "880",
			  "LNEdesigndens": 0,
			  "LNEpwht": false,
			  "LNE_VT": 100,
			  "LNE_RT": 0,
			  "LNE_MT": 0,
			  "LNE_PT": 0,
			  "LNE_UT": 0,
			  "LNE_HT": 0,
			  "LNE_MI": 0,
			  "LNEtestpack": "SP Service TP#5",
			  "LNEtesttype": "Service",
			  "LNEtestmed": "N/A",
			  "LNEcolor": "N/A",
			  "LNEtracing": "N/A",
			  "LNEinsulation": false,
			  "LNEInstype": "N/A",
			  "LNE_CA": 0.0625,
			  "LNEflgrating": "150lb",
			  "INRidno": 1,
			  "LNE_pickme": false
			 },
			 {
			  "id": 4,
			  "LNEidedate": "02/17/2022",
			  "LNEno": "Line-057-J-P376",
			  "LNEsystem": "MECHANICAL",
			  "LNEsysdes": "ML",
			  "LNEsyscode": "API650",
			  "LNEoptemp": 0,
			  "LNEdesigndens": 0,
			  "LNEpwht": false,
			  "LNE_VT": 100,
			  "LNE_RT": 0,
			  "LNE_MT": 0,
			  "LNE_PT": 0,
			  "LNE_UT": 0,
			  "LNE_HT": 0,
			  "LNE_MI": 0,
			  "LNEtestpress": 0,
			  "LNEinsulation": false,
			  "LNE_CA": 0,
			  "INRidno": 2,
			  "LNE_pickme": false
			 },
			 {
			  "id": 33,
			  "LNEidedate": "05/22/2022",
			  "LNEno": "Line-063-PP-P20",
			  "LNEFrom": "PP-P20-063",
			  "LNETo": "1ST FLOOR FERROUS SULPHATESTORAGE AREA HEATERS",
			  "LNEsystem": "Propane Piping",
			  "LNEsysdes": "PP",
			  "LNEsysarea": "510",
			  "LNErefpid": "395-B-050_B, ML510-B-023_B",
			  "LNErefpidrev": "0",
			  "LNEsyscode": "B149.2",
			  "LNEspec": "P20",
			  "LNEoptemp": 0,
			  "LNEdesignpress": "175",
			  "LNEdesigndens": 0,
			  "LNEpwht": false,
			  "LNE_VT": 100,
			  "LNE_RT": 0,
			  "LNE_MT": 0,
			  "LNE_PT": 0,
			  "LNE_UT": 0,
			  "LNE_HT": 0,
			  "LNE_MI": 0,
			  "LNEtestpack": "PP Pneumatic TP #1",
			  "LNEtesttype": "PNEUMATIC",
			  "LNEtestpress": 0,
			  "LNEcolor": "YELLOW, INTERNATIONAL PAINT NO. C115",
			  "LNEinsulation": false,
			  "LNEInstype": "N/A",
			  "LNE_CA": 0.0625,
			  "LNEflgrating": "N/A",
			  "INRidno": 3,
			  "LNE_pickme": false
			 },
			 {
			  "id": 34,
			  "LNEidedate": "05/22/2022",
			  "LNEno": "Line-067-PP-P20",
			  "LNEFrom": "PP-P20-067",
			  "LNETo": "2ND FLOOR FERROUS SULPHATESTORAGE AREA HEATERS",
			  "LNEsystem": "Propane Piping",
			  "LNEsysdes": "PP",
			  "LNEsysarea": "510",
			  "LNErefpid": "395-B-050_B, ML510-B-023_B",
			  "LNErefpidrev": "0",
			  "LNEsyscode": "B149.2",
			  "LNEspec": "P20",
			  "LNEoptemp": 0,
			  "LNEdesignpress": "175",
			  "LNEdesigndens": 0,
			  "LNEpwht": false,
			  "LNE_VT": 100,
			  "LNE_RT": 0,
			  "LNE_MT": 0,
			  "LNE_PT": 0,
			  "LNE_UT": 0,
			  "LNE_HT": 0,
			  "LNE_MI": 0,
			  "LNEtestpack": "PP Pneumatic TP#2",
			  "LNEtesttype": "PNEUMATIC",
			  "LNEtestpress": 0,
			  "LNEcolor": "YELLOW, INTERNATIONAL PAINT CO. C115",
			  "LNEinsulation": false,
			  "LNEInstype": "N/A",
			  "LNE_CA": 0.0625,
			  "LNEflgrating": "Need drawing",
			  "INRidno": 2,
			  "LNE_pickme": false
			 },
			 {
			  "id": 35,
			  "LNEidedate": "05/25/2022",
			  "LNEno": "Line-050-LS-P519",
			  "LNEFrom": "50-LS-01-507, 50-LS-01-509",
			  "LNETo": "25-LS-P50-519, 25-LS-P50-520",
			  "LNEsystem": "Lime Slurry",
			  "LNEsysdes": "LS",
			  "LNEsysarea": "510",
			  "LNErefpid": "ML510-K-064_B",
			  "LNErefpidrev": "0",
			  "LNEsyscode": "B31.3N",
			  "LNEspec": "P50",
			  "LNEoptemp": 0,
			  "LNEdesigndens": 0,
			  "LNEpwht": false,
			  "LNE_VT": 100,
			  "LNE_RT": 0,
			  "LNE_MT": 0,
			  "LNE_PT": 0,
			  "LNE_UT": 0,
			  "LNE_HT": 0,
			  "LNE_MI": 0,
			  "LNEtestpack": "LS Service Test",
			  "LNEtesttype": "SERVICE",
			  "LNEtestmed": "N/A",
			  "LNEtestpress": 0,
			  "LNEcolor": "N/A",
			  "LNEtracing": "N/A",
			  "LNEinsulation": false,
			  "LNEInstype": "N/A",
			  "LNEinsTm": "N/A",
			  "LNE_CWP": "1074-21-SP",
			  "LNE_CA": 0,
			  "LNEflgrating": "150",
			  "INRidno": 4,
			  "LNE_pickme": false
			 },
			 {
			  "id": 36,
			  "LNEidedate": "05/25/2022",
			  "LNEno": "Line-545-FH-P10",
			  "LNEFrom": "150-FH-P10-503",
			  "LNETo": "TP 06",
			  "LNEsystem": "MECHANICAL",
			  "LNEsysdes": "FH",
			  "LNEsysarea": "510",
			  "LNErefpid": "ML510-C-208_B",
			  "LNErefpidrev": "0",
			  "LNEsyscode": "B31.3N",
			  "LNEspec": "P10",
			  "LNEoptemp": 0,
			  "LNEdesigndens": 0,
			  "LNEpwht": false,
			  "LNE_VT": 100,
			  "LNE_RT": 0,
			  "LNE_MT": 0,
			  "LNE_PT": 0,
			  "LNE_UT": 0,
			  "LNE_HT": 0,
			  "LNE_MI": 0,
			  "LNEtesttype": "SERVICE",
			  "LNEtestpress": 0,
			  "LNEcolor": "N/A",
			  "LNEtracing": "N/A",
			  "LNEinsulation": false,
			  "LNEInstype": "N/A",
			  "LNEinsTm": "N/A",
			  "LNE_CWP": "1074-21-SP",
			  "LNE_CA": 0,
			  "LNEflgrating": "150",
			  "INRidno": 5,
			  "LNE_pickme": false
			 }
	],


	"bonds_table": [

			{
				"id": 1,
				"Bidedate": "3/25/22",
				"DWGidno": 3,
				"Bno": "EK100-2",
				"Bmat": "200g-Steel",
				"Bsize": "50mm",
				"Btm": "",
				"Btype": "Test bond",
				"Bpro": "",
				"Btrade": "Bonder",
				"Bdate": "3/25/22",
				"Binproinsp": false,
				"Bvt": "",
				"Blotno": "",
				"Brework": "",
				"Bcutout": false,
				"Brepno": "",
				"BVTinsp": "",
				"BVTdate": "",
				"RVTidno": 1,
				"Brepatt": "",
				"Bcomm": "",
			},

			{
				"id": 2,
				"Bidedate": "3/26/22",
				"DWGidno": 3,
				"Bno": "EK100-1",
				"Bmat": "200g-Steel",
				"Bsize": "30mm",
				"Btm": "",
				"Btype": "Test bond",
				"Bpro": "",
				"Btrade": "Bonder",
				"Bdate": "3/26/22",
				"Binproinsp": false,
				"Bvt": "",
				"Blotno": "",
				"Brework": "",
				"Bcutout": false,
				"Brepno": "",
				"BVTinsp": "",
				"BVTdate": "",
				"RVTidno": 6,
				"Brepatt": "",
				"Bcomm": "",
			},

			{
				"id": 3,
				"Bidedate": "3/25/22",
				"DWGidno": 3,
				"Bno": "B3-ER",
				"Bmat": "200g-Steel",
				"Bsize": "50mm",
				"Btm": "",
				"Btype": "Test bond",
				"Bpro": "",
				"Btrade": "Bonder",
				"Bdate": "3/25/22",
				"Binproinsp": false,
				"Bvt": "",
				"Blotno": "",
				"Brework": "",
				"Bcutout": false,
				"Brepno": "",
				"BVTinsp": "",
				"BVTdate": "",
				"RVTidno": 3,
				"Brepatt": "",
				"Bcomm": "",
			},

			{
				"id": 4,
				"Bidedate": "3/26/22",
				"DWGidno": 5,
				"Bno": "EFF-2D",
				"Bmat": "200g-Steel",
				"Bsize": "30mm",
				"Btm": "",
				"Btype": "Test bond",
				"Bpro": "",
				"Btrade": "Bonder",
				"Bdate": "3/26/22",
				"Binproinsp": false,
				"Bvt": "",
				"Blotno": "",
				"Brework": "",
				"Bcutout": false,
				"Brepno": "",
				"BVTinsp": "",
				"BVTdate": "",
				"RVTidno": 13,
				"Brepatt": "",
				"Bcomm": "",
			},

			{
				"id": 5,
				"Bidedate": "3/25/22",
				"DWGidno": 3,
				"Bno": "EK100-3",
				"Bmat": "200g-Steel",
				"Bsize": "50mm",
				"Btm": "",
				"Btype": "Test bond",
				"Bpro": "",
				"Btrade": "Bonder",
				"Bdate": "3/25/22",
				"Binproinsp": false,
				"Bvt": "",
				"Blotno": "",
				"Brework": "",
				"Bcutout": false,
				"Brepno": "",
				"BVTinsp": "",
				"BVTdate": "",
				"RVTidno": 15,
				"Brepatt": "",
				"Bcomm": "",
			},

			{
				"id": 6,
				"Bidedate": "3/26/22",
				"DWGidno": 9,
				"Bno": "DFE-234",
				"Bmat": "200g-Steel",
				"Bsize": "30mm",
				"Btm": "",
				"Btype": "Test bond",
				"Bpro": "",
				"Btrade": "Bonder",
				"Bdate": "3/26/22",
				"Binproinsp": false,
				"Bvt": "",
				"Blotno": "",
				"Brework": "",
				"Bcutout": false,
				"Brepno": "",
				"BVTinsp": "",
				"BVTdate": "",
				"RVTidno": 15,
				"Brepatt": "",
				"Bcomm": "",
			},

			{
				"id": 7,
				"Bidedate": "3/25/22",
				"DWGidno": 9,
				"Bno": "B5-ER",
				"Bmat": "200g-Steel",
				"Bsize": "50mm",
				"Btm": "",
				"Btype": "Test bond",
				"Bpro": "",
				"Btrade": "Bonder",
				"Bdate": "3/25/22",
				"Binproinsp": false,
				"Bvt": "",
				"Blotno": "",
				"Brework": "",
				"Bcutout": false,
				"Brepno": "",
				"BVTinsp": "",
				"BVTdate": "",
				"RVTidno": 7,
				"Brepatt": "",
				"Bcomm": "",
			},

			{
				"id": 8,
				"Bidedate": "3/26/22",
				"DWGidno": 5,
				"Bno": "ECF-5D",
				"Bmat": "200g-Steel",
				"Bsize": "30mm",
				"Btm": "",
				"Btype": "Test bond",
				"Bpro": "",
				"Btrade": "Bonder",
				"Bdate": "3/26/22",
				"Binproinsp": false,
				"Bvt": "",
				"Blotno": "",
				"Brework": "",
				"Bcutout": false,
				"Brepno": "",
				"BVTinsp": "",
				"BVTdate": "",
				"RVTidno": 1,
				"Brepatt": "",
				"Bcomm": "",
			},

			],

}